#!/usr/bin/env python

from absl import app, flags
import subprocess
import sys

FLAGS = flags.FLAGS

def setgflags():
	flags.DEFINE_integer('b', 100, "set beam size, (DEFAULT=100)")
	flags.DEFINE_bool('V', False, "use vienna parameters, (DEFAULT=FALSE)")
	flags.DEFINE_bool('sharpturn', False, "enable sharp turn in prediction, (DEFAULT=FALSE)")
	flags.DEFINE_bool('verbose', False, "print out energy of each loop in the structure, (DEFAULT=FALSE)")

def main(argv):
	use_vienna = FLAGS.V
	beamsize = str(FLAGS.b)
	is_sharpturn = '1' if FLAGS.sharpturn else '0'
	is_verbose = '1' if FLAGS.verbose else '0'

	if use_vienna:
		cmd = ['./linearfold_v' , beamsize, is_sharpturn, is_verbose]
	else:
		cmd = ['./linearfold_c' , beamsize, is_sharpturn, is_verbose]
	subprocess.call(cmd, stdin=sys.stdin)
	
if __name__ == '__main__':
	setgflags()
	app.run(main)

